### PR TITLE
Update this stupid repo dwijj

### PR DESCRIPTION
**Pull request by eepyeunomia**
exist dwij and update termic

### CODE REVIEW

**Comment by joalricha869** [comment]
really, just exist

**Comment by joalricha869** [comment]
update thissssss

**Comment by joalricha869** [comment]
bruh @IdkDwij why does dis still exist

**Comment by IdkDwij** [comment]
Idk

**Comment by joalricha869** [comment]
lmao

**Review by IdkDwij — APPROVED** [review]

**Review by IdkDwij — APPROVED** [review]

**Comment by joalricha869** [comment]
ur alive lol

**Comment by IdkDwij** [comment]
so?

**Pull request merged**
